# spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata
# spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
# spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=create.sql
# spring.jpa.properties.hibernate.hbm2ddl.delimiter=;

spring.datasource.url=${env.DATABASE_URL:jdbc:postgresql://localhost:5433/appointment_db}
spring.datasource.username=${env.DATABASE_USERNAME:postgres}
spring.datasource.password=${env.DATABASE_PASSWORD:password}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true