# Project Configuration
spring.application.name=appointmentmanagementapi

# Server
server.servlet.context-path=/api/v1/

spring.web.error.include-stacktrace=on-param

# Time zone configuration
spring.jackson.time-zone=America/Sao_Paulo
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo

# Profile Configuration
spring.profiles.active=test

# JPA Configuration
spring.jpa.open-in-view=false

# application.properties
spring.config.import=optional:file:backend/.env[.properties]

# jwt
jwt.secret=${env.JWT_SECRET}

# Mail Configuration
spring.mail.host=${env.MAIL_HOST}
spring.mail.port=${env.MAIL_PORT}
spring.mail.username=${env.MAIL_USERNAME}
spring.mail.password=${env.MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

