# Project Configuration
spring.application.name=appointmentmanagementapi

# Server
server.servlet.context-path=/api/v1/

spring.web.error.include-stacktrace=on-param

# Profile Configuration
spring.profiles.active=dev

# JPA Configuration
spring.jpa.open-in-view=false

# application.properties
spring.config.import=optional:file:backend/.env[.properties]

# jwt
jwt.secret=${env.JWT_SECRET:mysecretkey}

